kind: ImageStream
apiVersion: v1
metadata:
  name: s2i-angular-nginx
  annotations:
    openshift.io/display-name: "Angular / Nginx Builder Image"
triggers:
- type: ConfigChange
spec:
  lookupPolicy:
    local: true
  dockerImage: s2i-angular-nginx
  tags:
  - name: latest
    annotations:
      openshift.io/display-name: "Angular / Nginx Builder Image"
      description: "Build Angular apps with CLI and run them with nginx"
      iconClass: icon-angularjs
      labels:
        app: s2i-angular-nginx
      tags: "builder,js,angular,nginx"
      version: latest
    from:
      kind: DockerImage
      name: latest
    referencePolicy:
      type: Source
 